spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mailtest?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
  mail:
    protocol: smtp #邮件协议
    host: smtp.qq.com #qq邮箱 smtp 服务器地址
    port: 25
    username: 2541403556@qq.com #发件人邮箱
    password: vinevrrkqpkfechj # 授权码
    default-encoding: UTF-8 #编码字符集
    properties:
      mail:
        debug: true #开启后打印完整日志


mybatis:
  configuration:
    map-underscore-to-camel-case: true #开启驼峰映射
